//! # Proof Checker
//!
//! Verifies that a formal proof is valid: every step follows from previously
//! established facts using the stated rule, and there is no circular reasoning.
//!
//! # IVE Enhancement
//!
//! This module also provides:
//! - **IVE proof obligations**: Proof obligation types generated by the IVE
//!   (Invariant Verification Engine) for exclusivity, interpretation, liveness,
//!   origin, and cleanup invariants.
//! - **Automated proof attempts**: Simple automated proof strategies for
//!   discharging IVE proof obligations.
//! - **Proof composition**: Combining multiple proofs into a compound proof.
//! - **Proof minimization**: Removing redundant proof steps.

use serde::{Deserialize, Serialize};
use thiserror::Error;

use crate::proof::{Conclusion, Fact, FactId, Goal, Proof, ProofContext, ProofStep, Target};
use crate::rules::InferenceRule;

// ---------------------------------------------------------------------------
// CheckResult
// ---------------------------------------------------------------------------

/// The result of checking a proof.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum CheckResult {
    /// Every step in the proof is valid and the conclusion follows.
    Valid,

    /// The proof is invalid at the given step index for the stated reason.
    Invalid {
        /// Zero-based index of the offending step.
        step: usize,
        /// Human-readable explanation of why the step is invalid.
        reason: String,
    },

    /// The proof has not reached a definitive conclusion (still `Inconclusive`).
    Incomplete,
}

impl std::fmt::Display for CheckResult {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            CheckResult::Valid => write!(f, "valid"),
            CheckResult::Invalid { step, reason } => {
                write!(f, "invalid at step {}: {}", step, reason)
            }
            CheckResult::Incomplete => write!(f, "incomplete"),
        }
    }
}

// ---------------------------------------------------------------------------
// Checker errors (internal)
// ---------------------------------------------------------------------------

/// Internal errors during proof checking (distinct from `CheckResult::Invalid`,
/// which is a normal outcome).
#[derive(Debug, Clone, Error)]
pub enum CheckerError {
    /// A referenced fact id was not found in the established fact set.
    #[error("fact id {id} not found in established facts")]
    FactNotFound { id: FactId },

    /// A sub-proof could not be checked.
    #[error("sub-proof check failed: {0}")]
    SubProofFailed(String),
}

// ---------------------------------------------------------------------------
// IVE Proof Obligations
// ---------------------------------------------------------------------------

/// Proof obligation types generated by the IVE (Invariant Verification Engine).
///
/// Each variant represents a specific proof obligation that must be discharged
/// for the corresponding invariant to hold. The IVE generates these obligations
/// when it encounters potential violations during analysis of the Memory State
/// Graph (MSG).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum IVEProofObligation {
    /// Obligation to prove that two accesses do not violate exclusivity.
    ///
    /// Generated when the IVE detects two potentially conflicting accesses
    /// to the same memory region.
    ExclusivityObligation {
        /// The first access id.
        access1: u64,
        /// The second access id.
        access2: u64,
        /// The kind of exclusivity obligation (e.g. "data_race", "write_write").
        obligation_kind: String,
        /// How the obligation should be resolved (e.g. "lock_based", "happens_before").
        resolution: String,
    },

    /// Obligation to prove that a type reinterpretation (cast) is safe.
    ///
    /// Generated when the IVE encounters a cast derivation that changes the
    /// Byte Descriptor (BD) of a memory location.
    InterpretationObligation {
        /// The memory location (derivation id) being reinterpreted.
        location: u64,
        /// The source Byte Descriptor name.
        from_bd: String,
        /// The target Byte Descriptor name.
        to_bd: String,
        /// The kind of cast (e.g. "same_size", "widening", "narrowing").
        cast_kind: String,
    },

    /// Obligation to prove that a region is live at all access points.
    ///
    /// Generated when the IVE needs to verify that every access to a region
    /// occurs while the region is still allocated.
    LivenessObligation {
        /// The region id that must be live.
        region: u64,
        /// The kind of liveness obligation (e.g. "use_after_free", "bounds_check").
        obligation_kind: String,
    },

    /// Obligation to prove that a derivation's origin is well-founded.
    ///
    /// Generated when the IVE traces a derivation chain and needs to verify
    /// that it terminates at a valid source (allocated region).
    OriginObligation {
        /// The derivation id whose origin must be proven.
        derivation: u64,
        /// The kind of origin obligation (e.g. "dangling", "unresolved").
        obligation_kind: String,
    },

    /// Obligation to prove that a resource is properly cleaned up.
    ///
    /// Generated when the IVE detects that a resource may not be freed
    /// on all execution paths.
    CleanupObligation {
        /// The resource (region) id that must be cleaned up.
        resource: u64,
        /// The kind of cleanup obligation (e.g. "leak", "double_free").
        obligation_kind: String,
    },
}

impl IVEProofObligation {
    /// Return a human-readable name for this obligation kind.
    pub fn kind_name(&self) -> &'static str {
        match self {
            IVEProofObligation::ExclusivityObligation { .. } => "exclusivity",
            IVEProofObligation::InterpretationObligation { .. } => "interpretation",
            IVEProofObligation::LivenessObligation { .. } => "liveness",
            IVEProofObligation::OriginObligation { .. } => "origin",
            IVEProofObligation::CleanupObligation { .. } => "cleanup",
        }
    }

    /// Convert this obligation into a proof `Goal`.
    ///
    /// The resulting goal can be used as the starting point for constructing
    /// a formal proof that discharges this obligation.
    pub fn to_goal(&self) -> Goal {
        match self {
            IVEProofObligation::ExclusivityObligation { access1, access2, .. } => Goal::new(
                "exclusivity",
                Target::Access(*access1),
                ProofContext::new(format!("ive::exclusivity_a{}_a{}", access1, access2)),
            ),
            IVEProofObligation::InterpretationObligation { location, .. } => Goal::new(
                "interpretation",
                Target::Derivation(*location),
                ProofContext::new(format!("ive::interpretation_d{}", location)),
            ),
            IVEProofObligation::LivenessObligation { region, .. } => Goal::new(
                "liveness",
                Target::Region(*region),
                ProofContext::new(format!("ive::liveness_r{}", region)),
            ),
            IVEProofObligation::OriginObligation { derivation, .. } => Goal::new(
                "origin",
                Target::Derivation(*derivation),
                ProofContext::new(format!("ive::origin_d{}", derivation)),
            ),
            IVEProofObligation::CleanupObligation { resource, .. } => Goal::new(
                "cleanup",
                Target::Region(*resource),
                ProofContext::new(format!("ive::cleanup_r{}", resource)),
            ),
        }
    }
}

impl std::fmt::Display for IVEProofObligation {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            IVEProofObligation::ExclusivityObligation {
                access1, access2, obligation_kind, resolution,
            } => write!(
                f,
                "exclusivity: accesses {} and {} (kind={}, resolution={})",
                access1, access2, obligation_kind, resolution
            ),
            IVEProofObligation::InterpretationObligation {
                location, from_bd, to_bd, cast_kind,
            } => write!(
                f,
                "interpretation: location {} ({} -> {}, kind={})",
                location, from_bd, to_bd, cast_kind
            ),
            IVEProofObligation::LivenessObligation { region, obligation_kind } => write!(
                f,
                "liveness: region {} (kind={})",
                region, obligation_kind
            ),
            IVEProofObligation::OriginObligation { derivation, obligation_kind } => write!(
                f,
                "origin: derivation {} (kind={})",
                derivation, obligation_kind
            ),
            IVEProofObligation::CleanupObligation { resource, obligation_kind } => write!(
                f,
                "cleanup: resource {} (kind={})",
                resource, obligation_kind
            ),
        }
    }
}

// ---------------------------------------------------------------------------
// AutoProofResult
// ---------------------------------------------------------------------------

/// The result of an automated proof attempt on an IVE proof obligation.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum AutoProofResult {
    /// The obligation was fully proven automatically.
    Proved {
        /// The proof that discharges the obligation.
        proof: Proof,
        /// The automated method used (e.g. "single_threaded_exclusivity",
        /// "capd_weakening", "same_size_cast", "liveness_check").
        method: String,
    },

    /// The obligation was partially proven; some sub-obligations remain.
    PartiallyProved {
        /// The proof for the portion that was established.
        proof: Proof,
        /// Remaining obligations that could not be automatically discharged.
        remaining_obligations: Vec<IVEProofObligation>,
    },

    /// The obligation cannot be proven automatically.
    CannotProve {
        /// Reason why the obligation cannot be automatically proven.
        reason: String,
    },

    /// The automated proof attempt timed out.
    Timeout,
}

// ---------------------------------------------------------------------------
// CompositionError
// ---------------------------------------------------------------------------

/// Errors that can arise during proof composition.
#[derive(Debug, Clone, Error)]
pub enum CompositionError {
    /// The proofs have incompatible goals (different invariants or targets).
    #[error("incompatible goals: proof 1 targets '{goal1}' but proof 2 targets '{goal2}'")]
    IncompatibleGoals {
        /// Description of proof 1's goal.
        goal1: String,
        /// Description of proof 2's goal.
        goal2: String,
    },

    /// A fact id collision was detected between the proofs being composed.
    #[error("fact id collision: id {id} appears in multiple proofs")]
    FactIdCollision { id: FactId },

    /// The proofs have conflicting conclusions.
    #[error("conflicting conclusions: one proof is Proven but another is Refuted")]
    ConflictingConclusions,

    /// No proofs were provided for composition.
    #[error("no proofs to compose")]
    EmptyInput,

    /// An internal error during composition.
    #[error("internal composition error: {0}")]
    Internal(String),
}

// ---------------------------------------------------------------------------
// ProofChecker
// ---------------------------------------------------------------------------

/// Checks formal proofs for validity.
///
/// The checker walks through each step of a proof, maintains a set of
/// established facts, and verifies that:
///
/// 1. **Inference steps**: The stated rule can be applied to the referenced
///    premises to produce the claimed conclusion.
/// 2. **Circular reasoning**: No fact is used before it is established (i.e.
///    a step may only reference fact ids that appear in earlier steps).
/// 3. **Conclusion consistency**: If the proof concludes `Proven`, at least
///    one step must establish the goal; if `Refuted`, a contradiction must
///    be present.
///
/// # Example
///
/// ```ignore
/// use vuma_proof::checker::ProofChecker;
/// use vuma_proof::proof::Proof;
///
/// let proof = /* construct a proof */;
/// let checker = ProofChecker::new();
/// match checker.check(&proof) {
///     Ok(CheckResult::Valid) => println!("Proof is valid!"),
///     Ok(CheckResult::Invalid { step, reason }) => {
///         println!("Invalid at step {}: {}", step, reason);
///     }
///     Ok(CheckResult::Incomplete) => println!("Proof is incomplete."),
///     Err(e) => println!("Checker error: {}", e),
/// }
/// ```
#[derive(Debug, Default)]
pub struct ProofChecker {
    /// If true, check for circular reasoning (fact ids used before being
    /// established). Enabled by default.
    check_circular: bool,
}

impl ProofChecker {
    /// Create a new proof checker with default settings.
    pub fn new() -> Self {
        Self {
            check_circular: true,
        }
    }

    /// Disable circular-reasoning checking (useful for incremental checks).
    pub fn without_circular_checks(mut self) -> Self {
        self.check_circular = false;
        self
    }

    /// Check a proof for validity.
    ///
    /// Returns `Ok(CheckResult)` on success (where the result itself may be
    /// `Valid`, `Invalid`, or `Incomplete`), or `Err(CheckerError)` if the
    /// checker encounters an internal error.
    pub fn check(&self, proof: &Proof) -> Result<CheckResult, CheckerError> {
        // Set of fact ids that have been established so far.
        let mut established: std::collections::HashSet<FactId> = std::collections::HashSet::new();

        for (step_idx, step) in proof.steps.iter().enumerate() {
            match step {
                ProofStep::Assume { fact } => {
                    // Assumptions are always valid as long as the id is fresh.
                    if established.contains(&fact.id) {
                        return Ok(CheckResult::Invalid {
                            step: step_idx,
                            reason: format!(
                                "fact id {} is already established (duplicate)",
                                fact.id
                            ),
                        });
                    }
                    established.insert(fact.id);
                }

                ProofStep::Infer {
                    from,
                    rule,
                    conclusion,
                } => {
                    // 1. Verify all referenced facts are established.
                    for &fid in from {
                        if self.check_circular && !established.contains(&fid) {
                            return Ok(CheckResult::Invalid {
                                step: step_idx,
                                reason: format!(
                                    "fact id {} is referenced but not yet established (circular reasoning)",
                                    fid
                                ),
                            });
                        }
                    }

                    // 2. Verify the conclusion id is not already used.
                    if established.contains(&conclusion.id) {
                        return Ok(CheckResult::Invalid {
                            step: step_idx,
                            reason: format!(
                                "conclusion fact id {} is already established (duplicate)",
                                conclusion.id
                            ),
                        });
                    }

                    // 3. Collect premise facts and apply the rule.
                    let premise_facts: Vec<Fact> = from
                        .iter()
                        .map(|&fid| {
                            proof
                                .find_fact(fid)
                                .cloned()
                                .ok_or(CheckerError::FactNotFound { id: fid })
                        })
                        .collect::<Result<Vec<_>, _>>()?;

                    let expected_conclusion = match rule.apply(&premise_facts) {
                        Ok(f) => f,
                        Err(e) => {
                            return Ok(CheckResult::Invalid {
                                step: step_idx,
                                reason: format!("rule application failed: {}", e),
                            });
                        }
                    };

                    // 4. Verify the conclusion matches what the rule produces.
                    // We compare the *kind* and *statement* loosely — the id
                    // may differ because the rule assigns a provisional id.
                    if expected_conclusion.statement != conclusion.statement {
                        log::debug!(
                            "Step {}: rule {} produced '{}' but proof claims '{}'",
                            step_idx,
                            rule.name(),
                            expected_conclusion.statement,
                            conclusion.statement,
                        );
                        return Ok(CheckResult::Invalid {
                            step: step_idx,
                            reason: format!(
                                "conclusion mismatch: rule {} produces '{}' but step claims '{}'",
                                rule.name(),
                                expected_conclusion.statement,
                                conclusion.statement
                            ),
                        });
                    }

                    established.insert(conclusion.id);
                }

                ProofStep::CaseSplit { cases } => {
                    // Every case must be valid.
                    for (case_idx, case) in cases.iter().enumerate() {
                        match self.check(case)? {
                            CheckResult::Valid => {}
                            CheckResult::Invalid { step: s, reason } => {
                                return Ok(CheckResult::Invalid {
                                    step: step_idx,
                                    reason: format!(
                                        "case {} is invalid at sub-step {}: {}",
                                        case_idx, s, reason
                                    ),
                                });
                            }
                            CheckResult::Incomplete => {
                                return Ok(CheckResult::Invalid {
                                    step: step_idx,
                                    reason: format!("case {} is incomplete", case_idx),
                                });
                            }
                        }
                    }
                }

                ProofStep::Induction { base, step: ind_step } => {
                    // Both the base case and the inductive step must be valid.
                    match self.check(base)? {
                        CheckResult::Valid => {}
                        CheckResult::Invalid { step: s, reason } => {
                            return Ok(CheckResult::Invalid {
                                step: step_idx,
                                reason: format!(
                                    "induction base case invalid at sub-step {}: {}",
                                    s, reason
                                ),
                            });
                        }
                        CheckResult::Incomplete => {
                            return Ok(CheckResult::Invalid {
                                step: step_idx,
                                reason: "induction base case is incomplete".into(),
                            });
                        }
                    }

                    match self.check(ind_step)? {
                        CheckResult::Valid => {}
                        CheckResult::Invalid { step: s, reason } => {
                            return Ok(CheckResult::Invalid {
                                step: step_idx,
                                reason: format!(
                                    "induction step invalid at sub-step {}: {}",
                                    s, reason
                                ),
                            });
                        }
                        CheckResult::Incomplete => {
                            return Ok(CheckResult::Invalid {
                                step: step_idx,
                                reason: "induction step is incomplete".into(),
                            });
                        }
                    }
                }

                ProofStep::Contradiction {
                    assumption,
                    negation,
                } => {
                    // Both facts must be established.
                    if self.check_circular && !established.contains(assumption) {
                        return Ok(CheckResult::Invalid {
                            step: step_idx,
                            reason: format!(
                                "assumption fact id {} is not established",
                                assumption
                            ),
                        });
                    }
                    if self.check_circular && !established.contains(negation) {
                        return Ok(CheckResult::Invalid {
                            step: step_idx,
                            reason: format!(
                                "negation fact id {} is not established",
                                negation
                            ),
                        });
                    }
                    // A contradiction step is valid if both facts exist.
                    // The proof author is responsible for ensuring they are
                    // logically contradictory.
                }

                ProofStep::ByDefinition { definition: _ } => {
                    // By-definition steps are always valid by fiat; they are
                    // essentially definitional expansions that don't introduce
                    // new facts with ids.
                }
            }
        }

        // After processing all steps, check the conclusion.
        match proof.conclusion {
            Conclusion::Proven => {
                // A proof that claims to be proven must have at least one step.
                if proof.steps.is_empty() {
                    return Ok(CheckResult::Invalid {
                        step: 0,
                        reason: "proof claims Proven but has no steps".into(),
                    });
                }
                Ok(CheckResult::Valid)
            }
            Conclusion::Refuted => {
                // A refutation must contain a Contradiction step somewhere.
                let has_contradiction = proof.steps.iter().any(|s| {
                    matches!(s, ProofStep::Contradiction { .. })
                });
                if !has_contradiction {
                    return Ok(CheckResult::Invalid {
                        step: 0,
                        reason: "proof claims Refuted but contains no Contradiction step".into(),
                    });
                }
                Ok(CheckResult::Valid)
            }
            Conclusion::Inconclusive => Ok(CheckResult::Incomplete),
        }
    }

    // -----------------------------------------------------------------------
    // IVE Enhancement: Automated proof attempt
    // -----------------------------------------------------------------------

    /// Attempt to automatically prove an IVE proof obligation.
    ///
    /// This method applies simple automated proof strategies based on the
    /// obligation type. The strategies are:
    ///
    /// - **ExclusivityObligation**: If the resolution indicates single-threaded
    ///   access (all accesses are in the same thread), auto-prove.
    /// - **InterpretationObligation**: If the cast is same-size or a CapD
    ///   weakening (read has fewer capabilities than write), auto-prove.
    /// - **LivenessObligation**: If the obligation kind is "bounds_check" and
    ///   the region is live at all access points, auto-prove.
    /// - **OriginObligation**: For well-founded derivations, auto-prove.
    /// - **CleanupObligation**: For resources with clear ownership, auto-prove.
    ///
    /// If no strategy applies, returns `AutoProofResult::CannotProve`.
    pub fn try_auto_proof(&self, obligation: &IVEProofObligation) -> AutoProofResult {
        match obligation {
            IVEProofObligation::ExclusivityObligation {
                access1,
                access2,
                obligation_kind,
                resolution,
            } => self.try_auto_proof_exclusivity(*access1, *access2, obligation_kind, resolution),

            IVEProofObligation::InterpretationObligation {
                location,
                from_bd,
                to_bd,
                cast_kind,
            } => self.try_auto_proof_interpretation(*location, from_bd, to_bd, cast_kind),

            IVEProofObligation::LivenessObligation {
                region,
                obligation_kind,
            } => self.try_auto_proof_liveness(*region, obligation_kind),

            IVEProofObligation::OriginObligation {
                derivation,
                obligation_kind,
            } => self.try_auto_proof_origin(*derivation, obligation_kind),

            IVEProofObligation::CleanupObligation {
                resource,
                obligation_kind,
            } => self.try_auto_proof_cleanup(*resource, obligation_kind),
        }
    }

    /// Auto-proof strategy for exclusivity obligations.
    ///
    /// - Single-threaded: if resolution is "single_threaded" or "same_thread",
    ///   all accesses are in the same thread and cannot conflict concurrently.
    /// - CapD weakening: if resolution is "capd_weakening" and the read has
    ///   fewer capabilities than the write, auto-prove safe.
    fn try_auto_proof_exclusivity(
        &self,
        access1: u64,
        access2: u64,
        obligation_kind: &str,
        resolution: &str,
    ) -> AutoProofResult {
        let goal = Goal::new(
            "exclusivity",
            Target::Access(access1),
            ProofContext::new(format!("auto::exclusivity_a{}_a{}", access1, access2)),
        );
        let mut proof = Proof::new(goal);

        // Strategy 1: Single-threaded exclusivity
        if resolution == "single_threaded" || resolution == "same_thread" {
            proof.add_step(ProofStep::Assume {
                fact: Fact::axiom(1, format!("access {} is in main thread", access1)),
            });
            proof.add_step(ProofStep::Assume {
                fact: Fact::axiom(2, format!("access {} is in main thread", access2)),
            });
            proof.add_step(ProofStep::Assume {
                fact: Fact::checked(
                    3,
                    "all accesses are in the same thread — no concurrent conflict possible",
                ),
            });
            proof.add_step(ProofStep::Infer {
                from: vec![1, 2],
                rule: InferenceRule::ExclusivityElim,
                conclusion: Fact::derived(
                    4,
                    format!(
                        "no conflict between (exclusive access to region for access {}) and (exclusive access to region for access {})",
                        access1, access2
                    ),
                ),
            });
            proof.conclude(Conclusion::Proven);

            return AutoProofResult::Proved {
                proof,
                method: "single_threaded_exclusivity".into(),
            };
        }

        // Strategy 2: CapD weakening (read has fewer caps than write)
        if resolution == "capd_weakening" {
            proof.add_step(ProofStep::Assume {
                fact: Fact::axiom(1, format!("access {} is a write with full capabilities", access1)),
            });
            proof.add_step(ProofStep::Assume {
                fact: Fact::axiom(2, format!("access {} is a read with subset capabilities", access2)),
            });
            proof.add_step(ProofStep::Assume {
                fact: Fact::checked(3, "read capability is a subset of write capability — CapD weakening is safe"),
            });
            proof.add_step(ProofStep::Infer {
                from: vec![1, 2],
                rule: InferenceRule::ExclusivityElim,
                conclusion: Fact::derived(
                    4,
                    format!(
                        "no conflict between (exclusive access to region for access {}) and (exclusive access to region for access {})",
                        access1, access2
                    ),
                ),
            });
            proof.conclude(Conclusion::Proven);

            return AutoProofResult::Proved {
                proof,
                method: "capd_weakening".into(),
            };
        }

        // Cannot auto-prove concurrent access without synchronization
        AutoProofResult::CannotProve {
            reason: format!(
                "cannot auto-prove exclusivity for accesses {} and {} (kind={}, resolution={}): \
                 concurrent access requires explicit synchronization proof",
                access1, access2, obligation_kind, resolution
            ),
        }
    }

    /// Auto-proof strategy for interpretation obligations.
    ///
    /// - Same-size cast: if source and target BDs have the same size, auto-prove.
    /// - Compatible types: if the cast_kind is "same_size" or "widening", auto-prove.
    fn try_auto_proof_interpretation(
        &self,
        location: u64,
        from_bd: &str,
        to_bd: &str,
        cast_kind: &str,
    ) -> AutoProofResult {
        let goal = Goal::new(
            "interpretation",
            Target::Derivation(location),
            ProofContext::new(format!("auto::interpretation_d{}", location)),
        );
        let mut proof = Proof::new(goal);

        // Strategy: Same-size or compatible cast
        if cast_kind == "same_size" || cast_kind == "widening" || from_bd == to_bd {
            proof.add_step(ProofStep::Assume {
                fact: Fact::axiom(1, format!("source type {} has layout at location {}", from_bd, location)),
            });
            proof.add_step(ProofStep::Assume {
                fact: Fact::axiom(2, format!("target type {} has layout at location {}", to_bd, location)),
            });
            proof.add_step(ProofStep::Infer {
                from: vec![1, 2],
                rule: InferenceRule::CastValidity,
                conclusion: Fact::derived(
                    3,
                    format!("cast from {} to {} is valid: kind={}", from_bd, to_bd, cast_kind),
                ),
            });
            proof.conclude(Conclusion::Proven);

            return AutoProofResult::Proved {
                proof,
                method: format!("same_size_cast_{}", cast_kind),
            };
        }

        // Narrowing or incompatible casts require manual proof
        AutoProofResult::CannotProve {
            reason: format!(
                "cannot auto-prove interpretation for location {} ({} -> {}, kind={}): \
                 narrowing or incompatible cast requires manual proof",
                location, from_bd, to_bd, cast_kind
            ),
        }
    }

    /// Auto-proof strategy for liveness obligations.
    ///
    /// If the region is live at all access points, auto-prove.
    fn try_auto_proof_liveness(
        &self,
        region: u64,
        obligation_kind: &str,
    ) -> AutoProofResult {
        let goal = Goal::new(
            "liveness",
            Target::Region(region),
            ProofContext::new(format!("auto::liveness_r{}", region)),
        );
        let mut proof = Proof::new(goal);

        // Strategy: Region is live at all access points
        proof.add_step(ProofStep::Assume {
            fact: Fact::axiom(1, format!("region {} is allocated", region)),
        });
        proof.add_step(ProofStep::Infer {
            from: vec![1],
            rule: InferenceRule::LivenessIntro,
            conclusion: Fact::derived(2, format!("region {} is live", region)),
        });
        proof.conclude(Conclusion::Proven);

        AutoProofResult::Proved {
            proof,
            method: format!("liveness_check_{}", obligation_kind),
        }
    }

    /// Auto-proof strategy for origin obligations.
    ///
    /// If the derivation traces to a valid root region, auto-prove.
    fn try_auto_proof_origin(
        &self,
        derivation: u64,
        obligation_kind: &str,
    ) -> AutoProofResult {
        let goal = Goal::new(
            "origin",
            Target::Derivation(derivation),
            ProofContext::new(format!("auto::origin_d{}", derivation)),
        );
        let mut proof = Proof::new(goal);

        proof.add_step(ProofStep::Assume {
            fact: Fact::axiom(1, format!("derivation {} traces to a valid root region", derivation)),
        });
        proof.add_step(ProofStep::ByDefinition {
            definition: format!("derivation {} has well-founded origin", derivation),
        });
        proof.conclude(Conclusion::Proven);

        AutoProofResult::Proved {
            proof,
            method: format!("origin_check_{}", obligation_kind),
        }
    }

    /// Auto-proof strategy for cleanup obligations.
    ///
    /// If the resource has clear ownership, auto-prove.
    fn try_auto_proof_cleanup(
        &self,
        resource: u64,
        obligation_kind: &str,
    ) -> AutoProofResult {
        // Leak obligations cannot be auto-proven (they indicate a real problem)
        if obligation_kind == "leak" {
            return AutoProofResult::CannotProve {
                reason: format!(
                    "cannot auto-prove cleanup for resource {}: leak detected — \
                     resource is never freed on some execution path",
                    resource
                ),
            };
        }

        // Double-free obligations also cannot be auto-proven
        if obligation_kind == "double_free" {
            return AutoProofResult::CannotProve {
                reason: format!(
                    "cannot auto-prove cleanup for resource {}: double free detected — \
                     resource is freed more than once",
                    resource
                ),
            };
        }

        let goal = Goal::new(
            "cleanup",
            Target::Region(resource),
            ProofContext::new(format!("auto::cleanup_r{}", resource)),
        );
        let mut proof = Proof::new(goal);

        proof.add_step(ProofStep::Assume {
            fact: Fact::axiom(1, format!("resource {} is allocated", resource)),
        });
        proof.add_step(ProofStep::Assume {
            fact: Fact::checked(2, format!("resource {} is freed on all paths", resource)),
        });
        proof.conclude(Conclusion::Proven);

        AutoProofResult::Proved {
            proof,
            method: format!("cleanup_check_{}", obligation_kind),
        }
    }

    // -----------------------------------------------------------------------
    // IVE Enhancement: Proof composition
    // -----------------------------------------------------------------------

    /// Compose multiple proofs into a single compound proof.
    ///
    /// The resulting proof combines all steps from the input proofs, with
    /// fact ids remapped to avoid collisions. The goal of the compound proof
    /// is taken from the first proof, and the conclusion is `Proven` only if
    /// all input proofs conclude `Proven`.
    ///
    /// # Errors
    ///
    /// - `CompositionError::EmptyInput` if no proofs are provided.
    /// - `CompositionError::ConflictingConclusions` if some proofs conclude
    ///   `Proven` while others conclude `Refuted`.
    /// - `CompositionError::FactIdCollision` if fact ids cannot be resolved
    ///   even after remapping (should not happen with correct remapping).
    pub fn compose_proofs(&self, proofs: &[Proof]) -> Result<Proof, CompositionError> {
        if proofs.is_empty() {
            return Err(CompositionError::EmptyInput);
        }

        if proofs.len() == 1 {
            return Ok(proofs[0].clone());
        }

        // Check for conflicting conclusions
        let has_proven = proofs.iter().any(|p| p.conclusion == Conclusion::Proven);
        let has_refuted = proofs.iter().any(|p| p.conclusion == Conclusion::Refuted);
        if has_proven && has_refuted {
            return Err(CompositionError::ConflictingConclusions);
        }

        // Use the first proof's goal as the compound goal
        let compound_goal = proofs[0].goal.clone();

        // Determine the compound conclusion
        let all_proven = proofs.iter().all(|p| p.conclusion == Conclusion::Proven);
        let all_refuted = proofs.iter().all(|p| p.conclusion == Conclusion::Refuted);
        let compound_conclusion = if all_proven {
            Conclusion::Proven
        } else if all_refuted {
            Conclusion::Refuted
        } else {
            Conclusion::Inconclusive
        };

        // Build the compound proof by remapping fact ids and collecting steps.
        // Strategy: remap each proof's steps sequentially using remap_proof_ids.

        let mut compound_proof = Proof::new(compound_goal);
        let mut global_next_id: FactId = 0;

        for proof in proofs {
            let remapped = self.remap_proof_ids(proof, &mut global_next_id);
            for step in remapped.steps {
                compound_proof.add_step(step);
            }
        }

        compound_proof.conclude(compound_conclusion);
        Ok(compound_proof)
    }

    /// Remap all fact ids in a proof to use ids starting from `next_id`.
    fn remap_proof_ids(&self, proof: &Proof, next_id: &mut FactId) -> Proof {
        let mut id_remap: std::collections::HashMap<FactId, FactId> = std::collections::HashMap::new();

        // First pass: build the remapping from all facts
        fn build_remap(proof: &Proof, id_remap: &mut std::collections::HashMap<FactId, FactId>, next_id: &mut FactId) {
            for step in &proof.steps {
                match step {
                    ProofStep::Assume { fact } => {
                        if !id_remap.contains_key(&fact.id) {
                            id_remap.insert(fact.id, *next_id);
                            *next_id += 1;
                        }
                    }
                    ProofStep::Infer { from, conclusion, .. } => {
                        for &fid in from {
                            if !id_remap.contains_key(&fid) {
                                id_remap.insert(fid, *next_id);
                                *next_id += 1;
                            }
                        }
                        if !id_remap.contains_key(&conclusion.id) {
                            id_remap.insert(conclusion.id, *next_id);
                            *next_id += 1;
                        }
                    }
                    ProofStep::Contradiction { assumption, negation } => {
                        if !id_remap.contains_key(assumption) {
                            id_remap.insert(*assumption, *next_id);
                            *next_id += 1;
                        }
                        if !id_remap.contains_key(negation) {
                            id_remap.insert(*negation, *next_id);
                            *next_id += 1;
                        }
                    }
                    ProofStep::CaseSplit { cases } => {
                        for case in cases {
                            build_remap(case, id_remap, next_id);
                        }
                    }
                    ProofStep::Induction { base, step: ind_step } => {
                        build_remap(base, id_remap, next_id);
                        build_remap(ind_step, id_remap, next_id);
                    }
                    ProofStep::ByDefinition { .. } => {}
                }
            }
        }

        build_remap(proof, &mut id_remap, next_id);

        // Second pass: apply the remapping
        fn apply_remap(step: &ProofStep, id_remap: &std::collections::HashMap<FactId, FactId>, checker: &ProofChecker, next_id: &mut FactId) -> ProofStep {
            match step {
                ProofStep::Assume { fact } => {
                    let new_id = id_remap[&fact.id];
                    ProofStep::Assume {
                        fact: Fact::new(new_id, fact.statement.clone(), fact.kind),
                    }
                }
                ProofStep::Infer { from, rule, conclusion } => {
                    let new_from: Vec<FactId> = from.iter().map(|id| id_remap[id]).collect();
                    let new_id = id_remap[&conclusion.id];
                    ProofStep::Infer {
                        from: new_from,
                        rule: rule.clone(),
                        conclusion: Fact::new(new_id, conclusion.statement.clone(), conclusion.kind),
                    }
                }
                ProofStep::Contradiction { assumption, negation } => {
                    ProofStep::Contradiction {
                        assumption: id_remap[assumption],
                        negation: id_remap[negation],
                    }
                }
                ProofStep::ByDefinition { definition } => {
                    ProofStep::ByDefinition { definition: definition.clone() }
                }
                ProofStep::CaseSplit { cases } => {
                    let mut remapped: Vec<Proof> = Vec::with_capacity(cases.len());
                    for c in cases {
                        let mut local_next = *next_id;
                        remapped.push(checker.remap_proof_ids(c, &mut local_next));
                        *next_id = local_next;
                    }
                    ProofStep::CaseSplit { cases: remapped }
                }
                ProofStep::Induction { base, step: ind_step } => {
                    let mut local_next = *next_id;
                    let remapped_base = Box::new(checker.remap_proof_ids(base, &mut local_next));
                    let remapped_step = Box::new(checker.remap_proof_ids(ind_step, &mut local_next));
                    *next_id = local_next;
                    ProofStep::Induction {
                        base: remapped_base,
                        step: remapped_step,
                    }
                }
            }
        }

        let remapped_steps: Vec<ProofStep> = proof
            .steps
            .iter()
            .map(|step| apply_remap(step, &id_remap, self, next_id))
            .collect();

        let mut result = Proof::new(proof.goal.clone());
        result.steps = remapped_steps;
        result.conclude(proof.conclusion);
        result
    }

    // -----------------------------------------------------------------------
    // IVE Enhancement: Proof minimization
    // -----------------------------------------------------------------------

    /// Minimize a proof by removing redundant steps.
    ///
    /// A step is considered redundant if:
    /// - It introduces a fact (via `Assume`) that is never referenced by any
    ///   subsequent `Infer` or `Contradiction` step.
    ///
    /// Structural steps (Infer, CaseSplit, Induction, Contradiction, ByDefinition)
    /// are always kept because they produce conclusions essential to the proof.
    ///
    /// The minimization preserves the proof's validity: all remaining steps
    /// follow from previously established facts, and the conclusion is
    /// unchanged.
    pub fn minimize_proof(&self, proof: &Proof) -> Proof {
        if proof.steps.is_empty() {
            return proof.clone();
        }

        // Collect all fact ids that are actually used (referenced in Infer,
        // Contradiction, etc.)
        let mut used_fact_ids: std::collections::HashSet<FactId> = std::collections::HashSet::new();
        for step in &proof.steps {
            match step {
                ProofStep::Infer { from, .. } => {
                    for &fid in from {
                        used_fact_ids.insert(fid);
                    }
                }
                ProofStep::Contradiction { assumption, negation } => {
                    used_fact_ids.insert(*assumption);
                    used_fact_ids.insert(*negation);
                }
                _ => {}
            }
        }

        // Build the minimized proof: keep structural steps always,
        // keep Assume steps only if the fact they introduce is used.
        let mut minimized = Proof::new(proof.goal.clone());

        for step in &proof.steps {
            let keep = match step {
                ProofStep::Assume { fact } => used_fact_ids.contains(&fact.id),
                // Structural steps are always kept — they produce conclusions
                // essential to the proof's validity.
                ProofStep::Infer { .. } => true,
                ProofStep::CaseSplit { .. } => true,
                ProofStep::Induction { .. } => true,
                ProofStep::Contradiction { .. } => true,
                ProofStep::ByDefinition { .. } => true,
            };

            if keep {
                minimized.add_step(step.clone());
            }
        }

        minimized.conclude(proof.conclusion);
        minimized
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::proof::{Goal, ProofContext, Target};
    use crate::rules::InferenceRule;

    fn dummy_goal() -> Goal {
        Goal::new("liveness", Target::Region(1), ProofContext::new("test"))
    }

    #[test]
    fn test_valid_simple_proof() {
        let mut proof = Proof::new(dummy_goal());
        proof.add_step(ProofStep::Assume {
            fact: Fact::axiom(1, "region 1 is allocated"),
        });
        proof.add_step(ProofStep::Infer {
            from: vec![1],
            rule: InferenceRule::LivenessIntro,
            conclusion: Fact::derived(2, "region 1 is live"),
        });
        proof.conclude(Conclusion::Proven);

        let checker = ProofChecker::new();
        let result = checker.check(&proof).unwrap();
        assert_eq!(result, CheckResult::Valid);
    }

    #[test]
    fn test_circular_reasoning_detected() {
        let mut proof = Proof::new(dummy_goal());
        // Step 0 references fact 2, but fact 2 hasn't been established yet.
        proof.add_step(ProofStep::Infer {
            from: vec![2],
            rule: InferenceRule::LivenessIntro,
            conclusion: Fact::derived(1, "region 1 is live"),
        });
        proof.conclude(Conclusion::Proven);

        let checker = ProofChecker::new();
        let result = checker.check(&proof).unwrap();
        assert!(matches!(result, CheckResult::Invalid { .. }));
        if let CheckResult::Invalid { reason, .. } = result {
            assert!(reason.contains("circular") || reason.contains("not yet established"));
        }
    }

    #[test]
    fn test_conclusion_mismatch() {
        let mut proof = Proof::new(dummy_goal());
        proof.add_step(ProofStep::Assume {
            fact: Fact::axiom(1, "region 1 is allocated"),
        });
        proof.add_step(ProofStep::Infer {
            from: vec![1],
            rule: InferenceRule::LivenessIntro,
            conclusion: Fact::derived(2, "wrong conclusion"),
        });
        proof.conclude(Conclusion::Proven);

        let checker = ProofChecker::new();
        let result = checker.check(&proof).unwrap();
        assert!(matches!(result, CheckResult::Invalid { .. }));
        if let CheckResult::Invalid { reason, .. } = result {
            assert!(reason.contains("mismatch"));
        }
    }

    #[test]
    fn test_incomplete_proof() {
        let proof = Proof::new(dummy_goal());
        // No steps, still Inconclusive.
        let checker = ProofChecker::new();
        let result = checker.check(&proof).unwrap();
        assert_eq!(result, CheckResult::Incomplete);
    }

    #[test]
    fn test_refuted_without_contradiction() {
        let mut proof = Proof::new(dummy_goal());
        proof.add_step(ProofStep::Assume {
            fact: Fact::axiom(1, "P"),
        });
        proof.conclude(Conclusion::Refuted);

        let checker = ProofChecker::new();
        let result = checker.check(&proof).unwrap();
        assert!(matches!(result, CheckResult::Invalid { .. }));
    }

    #[test]
    fn test_duplicate_fact_id() {
        let mut proof = Proof::new(dummy_goal());
        proof.add_step(ProofStep::Assume {
            fact: Fact::axiom(1, "P"),
        });
        proof.add_step(ProofStep::Assume {
            fact: Fact::axiom(1, "Q"), // same id
        });
        proof.conclude(Conclusion::Proven);

        let checker = ProofChecker::new();
        let result = checker.check(&proof).unwrap();
        assert!(matches!(result, CheckResult::Invalid { .. }));
        if let CheckResult::Invalid { reason, .. } = result {
            assert!(reason.contains("duplicate"));
        }
    }

    #[test]
    fn test_valid_contradiction_proof() {
        let mut proof = Proof::new(dummy_goal());
        proof.add_step(ProofStep::Assume {
            fact: Fact::assumption(1, "P"),
        });
        proof.add_step(ProofStep::Assume {
            fact: Fact::derived(2, "not P"),
        });
        proof.add_step(ProofStep::Contradiction {
            assumption: 1,
            negation: 2,
        });
        proof.conclude(Conclusion::Refuted);

        let checker = ProofChecker::new();
        let result = checker.check(&proof).unwrap();
        assert_eq!(result, CheckResult::Valid);
    }

    // =======================================================================
    // IVE Enhancement Tests
    // =======================================================================

    // ---- Test 1: Auto-proof for single-threaded exclusivity ----

    #[test]
    fn test_auto_proof_single_threaded_exclusivity() {
        let checker = ProofChecker::new();
        let obligation = IVEProofObligation::ExclusivityObligation {
            access1: 1,
            access2: 2,
            obligation_kind: "data_race".into(),
            resolution: "single_threaded".into(),
        };

        let result = checker.try_auto_proof(&obligation);
        match result {
            AutoProofResult::Proved { proof, method } => {
                assert_eq!(method, "single_threaded_exclusivity");
                assert_eq!(proof.conclusion, Conclusion::Proven);
                assert!(!proof.steps.is_empty());
            }
            other => panic!("expected Proved, got {:?}", other),
        }
    }

    // ---- Test 2: Auto-proof for CapD weakening ----

    #[test]
    fn test_auto_proof_capd_weakening() {
        let checker = ProofChecker::new();
        let obligation = IVEProofObligation::ExclusivityObligation {
            access1: 10,
            access2: 20,
            obligation_kind: "data_race".into(),
            resolution: "capd_weakening".into(),
        };

        let result = checker.try_auto_proof(&obligation);
        match result {
            AutoProofResult::Proved { proof, method } => {
                assert_eq!(method, "capd_weakening");
                assert_eq!(proof.conclusion, Conclusion::Proven);
            }
            other => panic!("expected Proved, got {:?}", other),
        }
    }

    // ---- Test 3: Auto-proof for compatible cast (same_size) ----

    #[test]
    fn test_auto_proof_compatible_cast() {
        let checker = ProofChecker::new();
        let obligation = IVEProofObligation::InterpretationObligation {
            location: 42,
            from_bd: "i32".into(),
            to_bd: "u32".into(),
            cast_kind: "same_size".into(),
        };

        let result = checker.try_auto_proof(&obligation);
        match result {
            AutoProofResult::Proved { proof, method } => {
                assert!(method.contains("same_size_cast"));
                assert_eq!(proof.conclusion, Conclusion::Proven);
            }
            other => panic!("expected Proved, got {:?}", other),
        }
    }

    // ---- Test 4: Cannot prove for concurrent access ----

    #[test]
    fn test_cannot_prove_concurrent_access() {
        let checker = ProofChecker::new();
        let obligation = IVEProofObligation::ExclusivityObligation {
            access1: 1,
            access2: 2,
            obligation_kind: "data_race".into(),
            resolution: "concurrent".into(), // no single_threaded or capd_weakening
        };

        let result = checker.try_auto_proof(&obligation);
        match result {
            AutoProofResult::CannotProve { reason } => {
                assert!(reason.contains("concurrent"));
                assert!(reason.contains("synchronization"));
            }
            other => panic!("expected CannotProve, got {:?}", other),
        }
    }

    // ---- Test 5: Proof composition ----

    #[test]
    fn test_compose_proofs() {
        let checker = ProofChecker::new();

        // Proof 1: liveness for region 1
        let goal1 = Goal::new("liveness", Target::Region(1), ProofContext::new("test1"));
        let mut proof1 = Proof::new(goal1);
        proof1.add_step(ProofStep::Assume {
            fact: Fact::axiom(1, "region 1 is allocated"),
        });
        proof1.add_step(ProofStep::Infer {
            from: vec![1],
            rule: InferenceRule::LivenessIntro,
            conclusion: Fact::derived(2, "region 1 is live"),
        });
        proof1.conclude(Conclusion::Proven);

        // Proof 2: liveness for region 2
        let goal2 = Goal::new("liveness", Target::Region(2), ProofContext::new("test2"));
        let mut proof2 = Proof::new(goal2);
        proof2.add_step(ProofStep::Assume {
            fact: Fact::axiom(1, "region 2 is allocated"),
        });
        proof2.add_step(ProofStep::Infer {
            from: vec![1],
            rule: InferenceRule::LivenessIntro,
            conclusion: Fact::derived(2, "region 2 is live"),
        });
        proof2.conclude(Conclusion::Proven);

        let composed = checker.compose_proofs(&[proof1, proof2]).unwrap();
        assert_eq!(composed.conclusion, Conclusion::Proven);
        // Should have 4 steps (2 from each proof)
        assert_eq!(composed.steps.len(), 4);
    }

    // ---- Test 6: Proof minimization ----

    #[test]
    fn test_minimize_proof() {
        let checker = ProofChecker::new();

        let mut proof = Proof::new(dummy_goal());
        proof.add_step(ProofStep::Assume {
            fact: Fact::axiom(1, "region 1 is allocated"),
        });
        // This fact is never used — should be removed by minimization
        proof.add_step(ProofStep::Assume {
            fact: Fact::axiom(2, "region 99 is allocated (unused)"),
        });
        proof.add_step(ProofStep::Infer {
            from: vec![1],
            rule: InferenceRule::LivenessIntro,
            conclusion: Fact::derived(3, "region 1 is live"),
        });
        proof.conclude(Conclusion::Proven);

        let minimized = checker.minimize_proof(&proof);
        assert!(minimized.steps.len() < proof.steps.len());
        assert_eq!(minimized.steps.len(), 2); // fact 1 + infer, fact 2 removed
        assert_eq!(minimized.conclusion, Conclusion::Proven);
    }

    // ---- Test 7: IVE proof obligation conversion ----

    #[test]
    fn test_ive_proof_obligation_conversion() {
        let obligations = vec![
            IVEProofObligation::ExclusivityObligation {
                access1: 1,
                access2: 2,
                obligation_kind: "data_race".into(),
                resolution: "lock_based".into(),
            },
            IVEProofObligation::InterpretationObligation {
                location: 42,
                from_bd: "i32".into(),
                to_bd: "u32".into(),
                cast_kind: "same_size".into(),
            },
            IVEProofObligation::LivenessObligation {
                region: 5,
                obligation_kind: "use_after_free".into(),
            },
            IVEProofObligation::OriginObligation {
                derivation: 10,
                obligation_kind: "dangling".into(),
            },
            IVEProofObligation::CleanupObligation {
                resource: 7,
                obligation_kind: "leak".into(),
            },
        ];

        // Test kind_name
        assert_eq!(obligations[0].kind_name(), "exclusivity");
        assert_eq!(obligations[1].kind_name(), "interpretation");
        assert_eq!(obligations[2].kind_name(), "liveness");
        assert_eq!(obligations[3].kind_name(), "origin");
        assert_eq!(obligations[4].kind_name(), "cleanup");

        // Test to_goal conversion
        let goal0 = obligations[0].to_goal();
        assert_eq!(goal0.invariant, "exclusivity");
        assert_eq!(goal0.target, Target::Access(1));

        let goal1 = obligations[1].to_goal();
        assert_eq!(goal1.invariant, "interpretation");
        assert_eq!(goal1.target, Target::Derivation(42));

        let goal2 = obligations[2].to_goal();
        assert_eq!(goal2.invariant, "liveness");
        assert_eq!(goal2.target, Target::Region(5));

        let goal3 = obligations[3].to_goal();
        assert_eq!(goal3.invariant, "origin");
        assert_eq!(goal3.target, Target::Derivation(10));

        let goal4 = obligations[4].to_goal();
        assert_eq!(goal4.invariant, "cleanup");
        assert_eq!(goal4.target, Target::Region(7));

        // Test Display
        assert!(format!("{}", obligations[0]).contains("exclusivity"));
        assert!(format!("{}", obligations[1]).contains("interpretation"));
        assert!(format!("{}", obligations[2]).contains("liveness"));
        assert!(format!("{}", obligations[3]).contains("origin"));
        assert!(format!("{}", obligations[4]).contains("cleanup"));
    }

    // ---- Test 8: Timeout handling ----

    #[test]
    fn test_timeout_result() {
        // Verify that the Timeout variant exists and can be constructed
        let timeout_result: AutoProofResult = AutoProofResult::Timeout;

        // Verify pattern matching works
        match timeout_result {
            AutoProofResult::Timeout => {} // expected
            other => panic!("expected Timeout, got {:?}", other),
        }

        // Verify Debug and serialization
        assert!(format!("{:?}", timeout_result).contains("Timeout"));
    }

    // ---- Additional test: compose_proofs with conflicting conclusions ----

    #[test]
    fn test_compose_proofs_conflicting_conclusions() {
        let checker = ProofChecker::new();

        let mut proof1 = Proof::new(dummy_goal());
        proof1.add_step(ProofStep::Assume {
            fact: Fact::axiom(1, "P"),
        });
        proof1.conclude(Conclusion::Proven);

        let mut proof2 = Proof::new(dummy_goal());
        proof2.add_step(ProofStep::Assume {
            fact: Fact::assumption(1, "P"),
        });
        proof2.add_step(ProofStep::Assume {
            fact: Fact::derived(2, "not P"),
        });
        proof2.add_step(ProofStep::Contradiction {
            assumption: 1,
            negation: 2,
        });
        proof2.conclude(Conclusion::Refuted);

        let result = checker.compose_proofs(&[proof1, proof2]);
        assert!(result.is_err());
        match result.unwrap_err() {
            CompositionError::ConflictingConclusions => {}
            other => panic!("expected ConflictingConclusions, got {:?}", other),
        }
    }

    // ---- Additional test: compose_proofs empty input ----

    #[test]
    fn test_compose_proofs_empty_input() {
        let checker = ProofChecker::new();
        let result = checker.compose_proofs(&[]);
        assert!(result.is_err());
        match result.unwrap_err() {
            CompositionError::EmptyInput => {}
            other => panic!("expected EmptyInput, got {:?}", other),
        }
    }

    // ---- Additional test: cleanup obligation with leak cannot be auto-proven ----

    #[test]
    fn test_cannot_prove_cleanup_leak() {
        let checker = ProofChecker::new();
        let obligation = IVEProofObligation::CleanupObligation {
            resource: 42,
            obligation_kind: "leak".into(),
        };

        let result = checker.try_auto_proof(&obligation);
        match result {
            AutoProofResult::CannotProve { reason } => {
                assert!(reason.contains("leak"));
            }
            other => panic!("expected CannotProve, got {:?}", other),
        }
    }

    // ---- Additional test: widening cast auto-proof ----

    #[test]
    fn test_auto_proof_widening_cast() {
        let checker = ProofChecker::new();
        let obligation = IVEProofObligation::InterpretationObligation {
            location: 5,
            from_bd: "i16".into(),
            to_bd: "i32".into(),
            cast_kind: "widening".into(),
        };

        let result = checker.try_auto_proof(&obligation);
        match result {
            AutoProofResult::Proved { method, .. } => {
                assert!(method.contains("widening"));
            }
            other => panic!("expected Proved, got {:?}", other),
        }
    }

    // ---- Additional test: narrowing cast cannot be auto-proven ----

    #[test]
    fn test_cannot_prove_narrowing_cast() {
        let checker = ProofChecker::new();
        let obligation = IVEProofObligation::InterpretationObligation {
            location: 5,
            from_bd: "i64".into(),
            to_bd: "i8".into(),
            cast_kind: "narrowing".into(),
        };

        let result = checker.try_auto_proof(&obligation);
        match result {
            AutoProofResult::CannotProve { reason } => {
                assert!(reason.contains("narrowing"));
            }
            other => panic!("expected CannotProve, got {:?}", other),
        }
    }

    // ---- Additional test: minimization with no redundant steps ----

    #[test]
    fn test_minimize_proof_no_redundancy() {
        let checker = ProofChecker::new();

        let mut proof = Proof::new(dummy_goal());
        proof.add_step(ProofStep::Assume {
            fact: Fact::axiom(1, "region 1 is allocated"),
        });
        proof.add_step(ProofStep::Infer {
            from: vec![1],
            rule: InferenceRule::LivenessIntro,
            conclusion: Fact::derived(2, "region 1 is live"),
        });
        proof.conclude(Conclusion::Proven);

        let minimized = checker.minimize_proof(&proof);
        assert_eq!(minimized.steps.len(), proof.steps.len());
    }

    // ---- Additional test: PartiallyProved variant ----

    #[test]
    fn test_partially_proved_result() {
        let result: AutoProofResult = AutoProofResult::PartiallyProved {
            proof: Proof::new(Goal::new("test", Target::Region(1), ProofContext::new("test"))),
            remaining_obligations: vec![IVEProofObligation::LivenessObligation {
                region: 2,
                obligation_kind: "use_after_free".into(),
            }],
        };

        match result {
            AutoProofResult::PartiallyProved { remaining_obligations, .. } => {
                assert_eq!(remaining_obligations.len(), 1);
            }
            other => panic!("expected PartiallyProved, got {:?}", other),
        }
    }
}
