//! # Wasm32 Binary Validation Tests
//!
//! Verifies that the `.wasm` modules generated by the Wasm32 backend are
//! well-formed and can be loaded by Wasm runtimes.  Each test focuses on
//! one structural aspect of the Wasm binary format.
//!
//! # Test Matrix
//!
//! | # | Test                                        | What it validates                                   |
//! |---|---------------------------------------------|-----------------------------------------------------|
//! | 1 | test_wasm_magic_and_version                 | Header: 0x00 0x61 0x73 0x6D + version 0x01 0x00 0x00 0x00 |
//! | 2 | test_wasm_type_section_valid                | Type section contains valid func type entries (0x60 tag) |
//! | 3 | test_wasm_import_section_wasi               | Import section has proc_exit & fd_write from wasi_snapshot_preview1 |
//! | 4 | test_wasm_function_section_matches_types    | Function section type indices reference valid type entries |
//! | 5 | test_wasm_memory_section_min_pages          | Memory section declares at least 2 pages minimum    |
//! | 6 | test_wasm_global_section_heap_ptr           | Global section has mutable i32 __heap_ptr init'd to 65536 |
//! | 7 | test_wasm_export_section_start              | Export section exports `_start`                     |
//! | 8 | test_wasm_start_section_set                 | Start section is present and references a valid function |
//! | 9 | test_wasm_code_section_bodies_end           | Every code body in the code section ends with 0x0B (end) |
//! |10 | test_compile_to_wasm_returns_ok             | compile_to_wasm() returns Ok for valid IR programs  |
//! |11 | test_compile_to_wasm_valid_module           | Output of compile_to_wasm() is a well-formed module |
//! |12 | test_compile_to_wasm_simple_return_values   | Simple i32-returning programs compile and validate   |

use std::collections::{HashMap, HashSet};
use vuma_codegen::ir::{IRBlock, IRFunction, IRInstr, IRTerminator, IRType, IRValue};
use vuma_codegen::wasm32::{compile_to_wasm, decode_unsigned_leb128, decode_signed_leb128, WasmType};

// ===========================================================================
// Wasm binary section IDs
// ===========================================================================

const SECTION_TYPE: u8 = 1;
const SECTION_IMPORT: u8 = 2;
const SECTION_FUNCTION: u8 = 3;
const _SECTION_TABLE: u8 = 4;
const SECTION_MEMORY: u8 = 5;
const SECTION_GLOBAL: u8 = 6;
const SECTION_EXPORT: u8 = 7;
const SECTION_START: u8 = 8;
const _SECTION_ELEMENT: u8 = 9;
const SECTION_CODE: u8 = 10;
const _SECTION_DATA: u8 = 11;

const WASM_MAGIC: [u8; 4] = [0x00, 0x61, 0x73, 0x6D];
const WASM_VERSION: [u8; 4] = [0x01, 0x00, 0x00, 0x00];

// ===========================================================================
// Helpers
// ===========================================================================

/// Build a minimal IR function `fn main() -> i32 { return N; }`.
fn make_main_returning(value: i32) -> IRFunction {
    IRFunction {
        name: "main".to_string(),
        params: vec![],
        results: vec![],
        param_types: vec![],
        result_types: vec![IRType::I32],
        vregs: HashMap::new(),
        source_file: String::new(),
        blocks: vec![IRBlock {
            label: "entry".to_string(),
            instructions: vec![IRInstr::Ret {
                values: vec![IRValue::Immediate(value as i64)],
            }],
            terminator: IRTerminator::Return(vec![IRValue::Immediate(value as i64)]),
            predecessors: HashSet::new(),
            successors: HashSet::new(),
            source_line: 0,
        }],
    }
}

/// Build a minimal IR function `fn main() { }` (void return).
fn make_main_void() -> IRFunction {
    IRFunction {
        name: "main".to_string(),
        params: vec![],
        results: vec![],
        param_types: vec![],
        result_types: vec![],
        vregs: HashMap::new(),
        source_file: String::new(),
        blocks: vec![IRBlock {
            label: "entry".to_string(),
            instructions: vec![IRInstr::Ret { values: vec![] }],
            terminator: IRTerminator::Return(vec![]),
            predecessors: HashSet::new(),
            successors: HashSet::new(),
            source_line: 0,
        }],
    }
}

/// Compile the default test program (`fn main() -> i32 { return 0; }`) to Wasm.
fn compile_default_wasm() -> Vec<u8> {
    let func = make_main_returning(0);
    compile_to_wasm(&[func]).expect("default compilation should succeed")
}

/// Parsed representation of a Wasm section.
#[derive(Debug)]
struct ParsedSection {
    id: u8,
    content: Vec<u8>,
}

/// Parse all sections from a Wasm binary (after the 8-byte header).
fn parse_sections(wasm: &[u8]) -> Vec<ParsedSection> {
    assert!(wasm.len() >= 8, "Wasm binary must have at least 8 bytes");
    let mut sections = Vec::new();
    let mut offset = 8usize;

    while offset < wasm.len() {
        let section_id = wasm[offset];
        offset += 1;
        let (size, size_len) = decode_unsigned_leb128(&wasm[offset..]);
        offset += size_len;
        let section_end = offset + size as usize;
        let content = wasm[offset..section_end].to_vec();
        sections.push(ParsedSection {
            id: section_id,
            content,
        });
        offset = section_end;
    }

    sections
}

/// Find a section by ID among the parsed sections.
fn find_section<'a>(sections: &'a [ParsedSection], id: u8) -> Option<&'a ParsedSection> {
    sections.iter().find(|s| s.id == id)
}

/// Information extracted from the import section.
#[derive(Debug)]
struct ImportInfo {
    module: String,
    name: String,
    kind: u8,       // 0x00=function, 0x01=table, 0x02=memory, 0x03=global
    type_idx: u32,  // Only valid for function imports
}

/// Parse all imports from the import section content.
fn parse_imports(content: &[u8]) -> Vec<ImportInfo> {
    let mut imports = Vec::new();
    let mut offset = 0usize;
    let (count, count_len) = decode_unsigned_leb128(&content[offset..]);
    offset += count_len;

    for _ in 0..count {
        // Module name
        let (mod_len, ml_len) = decode_unsigned_leb128(&content[offset..]);
        offset += ml_len;
        let module = std::str::from_utf8(&content[offset..offset + mod_len as usize])
            .unwrap_or("")
            .to_string();
        offset += mod_len as usize;

        // Import name
        let (name_len, nl_len) = decode_unsigned_leb128(&content[offset..]);
        offset += nl_len;
        let name = std::str::from_utf8(&content[offset..offset + name_len as usize])
            .unwrap_or("")
            .to_string();
        offset += name_len as usize;

        // Kind
        let kind = content[offset];
        offset += 1;

        let mut type_idx = 0u32;
        if kind == 0x00 {
            // Function import: type index follows
            let (ti, ti_len) = decode_unsigned_leb128(&content[offset..]);
            offset += ti_len;
            type_idx = ti as u32;
        } else if kind == 0x01 {
            // Table: elem_type + limits
            offset += 1; // elem_type
            let (flags, fl) = decode_unsigned_leb128(&content[offset..]);
            offset += fl;
            let (_, ml) = decode_unsigned_leb128(&content[offset..]);
            offset += ml;
            if flags != 0 {
                let (_, xl) = decode_unsigned_leb128(&content[offset..]);
                offset += xl;
            }
        } else if kind == 0x02 {
            // Memory: limits
            let (flags, fl) = decode_unsigned_leb128(&content[offset..]);
            offset += fl;
            let (_, ml) = decode_unsigned_leb128(&content[offset..]);
            offset += ml;
            if flags != 0 {
                let (_, xl) = decode_unsigned_leb128(&content[offset..]);
                offset += xl;
            }
        } else if kind == 0x03 {
            // Global: val_type + mutability
            offset += 1; // val_type
            offset += 1; // mutable
        }

        imports.push(ImportInfo {
            module,
            name,
            kind,
            type_idx,
        });
    }

    imports
}

/// Information extracted from an export entry.
#[derive(Debug)]
struct ExportInfo {
    name: String,
    kind: u8,    // 0=function, 1=table, 2=memory, 3=global
    index: u32, // Not read directly but kept for structural completeness
}

/// Parse all exports from the export section content.
fn parse_exports(content: &[u8]) -> Vec<ExportInfo> {
    let mut exports = Vec::new();
    let mut offset = 0usize;
    let (count, count_len) = decode_unsigned_leb128(&content[offset..]);
    offset += count_len;

    for _ in 0..count {
        let (name_len, nl_len) = decode_unsigned_leb128(&content[offset..]);
        offset += nl_len;
        let name = std::str::from_utf8(&content[offset..offset + name_len as usize])
            .unwrap_or("")
            .to_string();
        offset += name_len as usize;

        let kind = content[offset];
        offset += 1;

        let (index, il) = decode_unsigned_leb128(&content[offset..]);
        offset += il;

        exports.push(ExportInfo {
            name,
            kind,
            index: index as u32,
        });
    }

    exports
}

// ===========================================================================
// Test 1: Magic and version
// ===========================================================================

/// Test: Verify the Wasm binary starts with the correct magic number
/// (0x00 0x61 0x73 0x6D = "\0asm") and version (0x01 0x00 0x00 0x00 = version 1).
#[test]
fn test_wasm_magic_and_version() {
    let wasm = compile_default_wasm();

    assert!(
        wasm.len() >= 8,
        "Wasm module must be at least 8 bytes, got {}",
        wasm.len()
    );

    assert_eq!(
        &wasm[0..4],
        &WASM_MAGIC,
        "Wasm magic should be 0x00 0x61 0x73 0x6D (\\0asm), got {:02X?}",
        &wasm[0..4]
    );

    assert_eq!(
        &wasm[4..8],
        &WASM_VERSION,
        "Wasm version should be 0x01 0x00 0x00 0x00, got {:02X?}",
        &wasm[4..8]
    );
}

// ===========================================================================
// Test 2: Type section — verifies function types are valid
// ===========================================================================

/// Test: Validate that the type section exists and contains well-formed
/// function type entries.  Each entry must start with the `0x60` func type
/// tag, followed by a parameter count, parameter types, result count, and
/// result types.
#[test]
fn test_wasm_type_section_valid() {
    let wasm = compile_default_wasm();
    let sections = parse_sections(&wasm);

    let type_section = find_section(&sections, SECTION_TYPE)
        .expect("Module should contain a type section (ID 1)");

    let content = &type_section.content;
    let mut offset = 0usize;

    let (num_types, count_len) = decode_unsigned_leb128(&content[offset..]);
    offset += count_len;

    assert!(
        num_types > 0,
        "Type section should contain at least one function type, got {}",
        num_types
    );

    // Validate each function type entry
    for i in 0..num_types {
        let tag = content[offset];
        assert_eq!(
            tag, 0x60,
            "Function type entry {} should start with tag 0x60, got {:#04X}",
            i, tag
        );
        offset += 1;

        // Parameter count
        let (param_count, pc_len) = decode_unsigned_leb128(&content[offset..]);
        offset += pc_len;

        // Validate each parameter type byte
        for j in 0..param_count {
            let ty_byte = content[offset];
            assert!(
                WasmType::from_byte(ty_byte).is_some(),
                "Parameter {} of type entry {} should be a valid Wasm type byte, got {:#04X}",
                j,
                i,
                ty_byte
            );
            offset += 1;
        }

        // Result count
        let (result_count, rc_len) = decode_unsigned_leb128(&content[offset..]);
        offset += rc_len;

        // Validate each result type byte
        for j in 0..result_count {
            let ty_byte = content[offset];
            assert!(
                WasmType::from_byte(ty_byte).is_some(),
                "Result {} of type entry {} should be a valid Wasm type byte, got {:#04X}",
                j,
                i,
                ty_byte
            );
            offset += 1;
        }
    }
}

// ===========================================================================
// Test 3: Import section — verifies WASI imports (proc_exit, fd_write)
// ===========================================================================

/// Test: Validate that the import section contains the required WASI imports:
/// - `wasi_snapshot_preview1.proc_exit` — for process termination
/// - `wasi_snapshot_preview1.fd_write`   — for stdout output
#[test]
fn test_wasm_import_section_wasi() {
    let wasm = compile_default_wasm();
    let sections = parse_sections(&wasm);

    let import_section = find_section(&sections, SECTION_IMPORT)
        .expect("Module should contain an import section (ID 2)");

    let imports = parse_imports(&import_section.content);

    // Check fd_write import
    let has_fd_write = imports.iter().any(|imp| {
        imp.module == "wasi_snapshot_preview1" && imp.name == "fd_write" && imp.kind == 0x00
    });
    assert!(
        has_fd_write,
        "Module should import wasi_snapshot_preview1.fd_write as a function"
    );

    // Check proc_exit import
    let has_proc_exit = imports.iter().any(|imp| {
        imp.module == "wasi_snapshot_preview1" && imp.name == "proc_exit" && imp.kind == 0x00
    });
    assert!(
        has_proc_exit,
        "Module should import wasi_snapshot_preview1.proc_exit as a function"
    );

    // There should be at least 2 WASI imports
    let wasi_count = imports
        .iter()
        .filter(|imp| imp.module == "wasi_snapshot_preview1")
        .count();
    assert!(
        wasi_count >= 2,
        "Module should have at least 2 WASI imports, found {}",
        wasi_count
    );

    // All WASI imports should be function imports (kind 0x00)
    for imp in &imports {
        if imp.module == "wasi_snapshot_preview1" {
            assert_eq!(
                imp.kind, 0x00,
                "WASI import '{}' should be a function import (kind 0x00), got kind {:#04X}",
                imp.name, imp.kind
            );
        }
    }
}

// ===========================================================================
// Test 4: Function section — verifies function indices match type section
// ===========================================================================

/// Test: Validate that the function section contains type indices that
/// reference valid entries in the type section.  The function section lists
/// type indices for locally-defined functions (excluding imports).
#[test]
fn test_wasm_function_section_matches_types() {
    let wasm = compile_default_wasm();
    let sections = parse_sections(&wasm);

    // Get the number of types from the type section
    let type_section = find_section(&sections, SECTION_TYPE)
        .expect("Module should contain a type section");
    let (num_types, _) = decode_unsigned_leb128(&type_section.content);

    // Parse the function section
    let func_section = find_section(&sections, SECTION_FUNCTION)
        .expect("Module should contain a function section (ID 3)");

    let content = &func_section.content;
    let mut offset = 0usize;
    let (num_funcs, count_len) = decode_unsigned_leb128(&content[offset..]);
    offset += count_len;

    assert!(
        num_funcs > 0,
        "Function section should list at least one function, got {}",
        num_funcs
    );

    // Each type index must be within bounds of the type section
    for i in 0..num_funcs {
        let (type_idx, ti_len) = decode_unsigned_leb128(&content[offset..]);
        offset += ti_len;

        assert!(
            type_idx < num_types,
            "Function {} references type index {}, but only {} types exist",
            i,
            type_idx,
            num_types
        );
    }
}

// ===========================================================================
// Test 5: Memory section — verifies at least 2 pages minimum
// ===========================================================================

/// Test: Validate that the memory section declares at least 2 pages (128 KiB)
/// of linear memory.  The Vuma Wasm32 backend reserves the first page for
/// globals/stack and the second page onwards for the heap.
#[test]
fn test_wasm_memory_section_min_pages() {
    let wasm = compile_default_wasm();
    let sections = parse_sections(&wasm);

    let mem_section = find_section(&sections, SECTION_MEMORY)
        .expect("Module should contain a memory section (ID 5)");

    let content = &mem_section.content;
    let mut offset = 0usize;

    let (num_memories, count_len) = decode_unsigned_leb128(&content[offset..]);
    offset += count_len;

    assert!(
        num_memories > 0,
        "Memory section should declare at least one memory"
    );

    // Parse the first (and typically only) memory entry
    let flags = content[offset];
    offset += 1;

    let (min_pages, min_len) = decode_unsigned_leb128(&content[offset..]);
    offset += min_len;

    // The Vuma backend allocates min:2, max:256 pages
    assert!(
        min_pages >= 2,
        "Memory should have at least 2 pages minimum, got {}",
        min_pages
    );

    // If max is specified (flags & 1), verify it's >= min
    if flags & 1 != 0 {
        let (max_pages, max_len) = decode_unsigned_leb128(&content[offset..]);
        let _ = offset; // offset updated for consistency but max_len branch ends here
        let _ = max_len;
        assert!(
            max_pages >= min_pages as u64,
            "Memory max pages ({}) should be >= min pages ({})",
            max_pages,
            min_pages
        );
    }
}

// ===========================================================================
// Test 6: Global section — verifies __heap_ptr global (mutable i32, init 65536)
// ===========================================================================

/// Test: Validate that the global section contains the `__heap_ptr` global
/// variable with the correct type (mutable i32) and initial value (65536,
/// which is the start of the second 64 KiB page in linear memory).
#[test]
fn test_wasm_global_section_heap_ptr() {
    let wasm = compile_default_wasm();
    let sections = parse_sections(&wasm);

    let global_section = find_section(&sections, SECTION_GLOBAL)
        .expect("Module should contain a global section (ID 6)");

    let content = &global_section.content;
    let mut offset = 0usize;

    let (num_globals, count_len) = decode_unsigned_leb128(&content[offset..]);
    offset += count_len;

    assert!(
        num_globals > 0,
        "Global section should contain at least one global variable"
    );

    // Look for the __heap_ptr global: mutable i32, init 65536
    let mut found_heap_ptr = false;

    for _ in 0..num_globals {
        let val_type = content[offset];
        offset += 1;
        let mutable = content[offset];
        offset += 1;

        // Parse the init expression
        let init_opcode = content[offset];
        offset += 1;

        let mut init_value: i64 = 0;
        if init_opcode == 0x41 {
            // i32.const
            let (val, val_len) = decode_signed_leb128(&content[offset..]);
            offset += val_len;
            init_value = val;
        } else if init_opcode == 0x42 {
            // i64.const
            let (val, val_len) = decode_signed_leb128(&content[offset..]);
            offset += val_len;
            init_value = val;
        } else {
            // Skip other init expression forms
            // For unknown opcodes, just skip to the end byte
            while offset < content.len() && content[offset] != 0x0B {
                offset += 1;
            }
        }

        // End byte of init expression
        let end_byte = content[offset];
        offset += 1;
        assert_eq!(
            end_byte, 0x0B,
            "Global init expression should end with 0x0B, got {:#04X}",
            end_byte
        );

        // Check for __heap_ptr: mutable i32 (0x7F) initialised to 65536
        if val_type == 0x7F && mutable == 0x01 && init_value == 65536 {
            found_heap_ptr = true;
        }
    }

    assert!(
        found_heap_ptr,
        "Global section should contain a mutable i32 global initialised to 65536 (__heap_ptr)"
    );
}

// ===========================================================================
// Test 7: Export section — verifies _start is exported
// ===========================================================================

/// Test: Validate that the export section exports `_start`, which is the
/// standard WASI entry point that Wasm runtimes invoke on module
/// instantiation.
#[test]
fn test_wasm_export_section_start() {
    let wasm = compile_default_wasm();
    let sections = parse_sections(&wasm);

    let export_section = find_section(&sections, SECTION_EXPORT)
        .expect("Module should contain an export section (ID 7)");

    let exports = parse_exports(&export_section.content);

    // _start must be exported as a function
    let has_start = exports.iter().any(|exp| {
        exp.name == "_start" && exp.kind == 0x00 // Function export
    });
    assert!(
        has_start,
        "Module should export '_start' as a function, found exports: {:?}",
        exports.iter().map(|e| &e.name).collect::<Vec<_>>()
    );

    // Also verify that 'main' is exported if we compiled a main function
    let has_main = exports.iter().any(|exp| exp.name == "main" && exp.kind == 0x00);
    assert!(
        has_main,
        "Module should export 'main' as a function, found exports: {:?}",
        exports.iter().map(|e| &e.name).collect::<Vec<_>>()
    );
}

// ===========================================================================
// Test 8: Start section — verifies start function is set
// ===========================================================================

/// Test: Validate that the start section is present and references a valid
/// function index.  The Vuma Wasm32 backend sets `_start` as the start
/// function, which is automatically called on module instantiation.
#[test]
fn test_wasm_start_section_set() {
    let wasm = compile_default_wasm();
    let sections = parse_sections(&wasm);

    let start_section = find_section(&sections, SECTION_START)
        .expect("Module should contain a start section (ID 8)");

    let content = &start_section.content;

    // The start section content is a single uLEB128 function index
    let (func_idx, consumed) = decode_unsigned_leb128(content);
    assert_eq!(
        consumed,
        content.len(),
        "Start section should contain exactly one function index"
    );

    // The start function index should be valid (non-zero, since 0 and 1
    // are WASI imports).  We need to count total functions.
    let mut total_funcs = 0u64;

    // Count imported functions
    if let Some(import_section) = find_section(&sections, SECTION_IMPORT) {
        let imports = parse_imports(&import_section.content);
        total_funcs += imports.iter().filter(|imp| imp.kind == 0x00).count() as u64;
    }

    // Count local functions
    if let Some(func_section) = find_section(&sections, SECTION_FUNCTION) {
        let (num_local, _) = decode_unsigned_leb128(&func_section.content);
        total_funcs += num_local;
    }

    assert!(
        func_idx < total_funcs,
        "Start function index {} should be less than total function count {}",
        func_idx,
        total_funcs
    );

    // The start function must have signature () -> () (type with 0 params, 0 results).
    // Find the function's type index and validate it.
    let num_imported_funcs = if let Some(import_section) = find_section(&sections, SECTION_IMPORT) {
        let imports = parse_imports(&import_section.content);
        imports.iter().filter(|imp| imp.kind == 0x00).count() as u64
    } else {
        0
    };

    // Get the type index for the start function
    let type_idx: u64 = if func_idx < num_imported_funcs {
        // It's an imported function — get type_idx from import section
        if let Some(import_section) = find_section(&sections, SECTION_IMPORT) {
            let imports = parse_imports(&import_section.content);
            let func_imports: Vec<_> = imports.iter().filter(|imp| imp.kind == 0x00).collect();
            func_imports[func_idx as usize].type_idx as u64
        } else {
            0
        }
    } else {
        // It's a local function — get type_idx from function section
        let local_idx = (func_idx - num_imported_funcs) as usize;
        if let Some(func_section) = find_section(&sections, SECTION_FUNCTION) {
            let mut off = 0usize;
            let (count, cl) = decode_unsigned_leb128(&func_section.content);
            off += cl;
            let mut found_type_idx: u64 = 0;
            for fi in 0..count {
                let (ti, til) = decode_unsigned_leb128(&func_section.content[off..]);
                off += til;
                if fi as usize == local_idx {
                    found_type_idx = ti;
                    break;
                }
            }
            found_type_idx
        } else {
            0
        }
    };

    // Validate the type signature is () -> ()
    if let Some(type_section) = find_section(&sections, SECTION_TYPE) {
        let (num_types, ntl) = decode_unsigned_leb128(&type_section.content);
        let mut off = ntl;
        for ti in 0..num_types {
            let tag = type_section.content[off];
            off += 1;
            assert_eq!(tag, 0x60, "Type entry {} should have func tag 0x60", ti);

            let (param_count, pcl) = decode_unsigned_leb128(&type_section.content[off..]);
            off += pcl;
            off += param_count as usize; // skip param types

            let (result_count, rcl) = decode_unsigned_leb128(&type_section.content[off..]);
            off += rcl;
            off += result_count as usize; // skip result types

            if ti == type_idx {
                assert_eq!(
                    param_count, 0,
                    "Start function type should have 0 parameters, got {}",
                    param_count
                );
                assert_eq!(
                    result_count, 0,
                    "Start function type should have 0 results, got {}",
                    result_count
                );
                break;
            }
        }
    }
}

// ===========================================================================
// Test 9: Code section — verifies function bodies end with 0x0B (end)
// ===========================================================================

/// Test: Validate that every function body in the code section ends with
/// the `0x0B` (end) opcode, as required by the Wasm binary format
/// specification.
#[test]
fn test_wasm_code_section_bodies_end() {
    let wasm = compile_default_wasm();
    let sections = parse_sections(&wasm);

    let code_section = find_section(&sections, SECTION_CODE)
        .expect("Module should contain a code section (ID 10)");

    let content = &code_section.content;
    let mut offset = 0usize;

    let (num_bodies, count_len) = decode_unsigned_leb128(&content[offset..]);
    offset += count_len;

    assert!(
        num_bodies > 0,
        "Code section should contain at least one function body"
    );

    for i in 0..num_bodies {
        let (body_size, bs_len) = decode_unsigned_leb128(&content[offset..]);
        offset += bs_len;

        let _body_start = offset;
        let body_end = offset + body_size as usize;

        // The last byte of the function body must be 0x0B (end opcode)
        let last_byte = content[body_end - 1];
        assert_eq!(
            last_byte, 0x0B,
            "Function body {} should end with 0x0B (end opcode), got {:#04X}",
            i, last_byte
        );

        offset = body_end;
    }
}

// ===========================================================================
// Test 10: compile_to_wasm() returns Ok for valid programs
// ===========================================================================

/// Test: Verify that `compile_to_wasm()` returns `Ok` for valid IR programs.
#[test]
fn test_compile_to_wasm_returns_ok() {
    // Simple i32 return
    let func = make_main_returning(42);
    let result = compile_to_wasm(&[func]);
    assert!(
        result.is_ok(),
        "compile_to_wasm should return Ok for a simple i32-returning function, got Err: {:?}",
        result
    );

    // Void return
    let func = make_main_void();
    let result = compile_to_wasm(&[func]);
    assert!(
        result.is_ok(),
        "compile_to_wasm should return Ok for a void function, got Err: {:?}",
        result
    );

    // No main function (should still succeed — exits with code 1)
    let func = IRFunction {
        name: "helper".to_string(),
        params: vec![],
        results: vec![],
        param_types: vec![],
        result_types: vec![IRType::I32],
        vregs: HashMap::new(),
        source_file: String::new(),
        blocks: vec![IRBlock {
            label: "entry".to_string(),
            instructions: vec![IRInstr::Ret {
                values: vec![IRValue::Immediate(7)],
            }],
            terminator: IRTerminator::Return(vec![IRValue::Immediate(7)]),
            predecessors: HashSet::new(),
            successors: HashSet::new(),
            source_line: 0,
        }],
    };
    let result = compile_to_wasm(&[func]);
    assert!(
        result.is_ok(),
        "compile_to_wasm should return Ok for a non-main function, got Err: {:?}",
        result
    );
}

// ===========================================================================
// Test 11: Output of compile_to_wasm() is a well-formed module
// ===========================================================================

/// Test: Verify that the output of `compile_to_wasm()` is a well-formed
/// Wasm module by checking that all required sections are present and the
/// module can be re-parsed without errors.
#[test]
fn test_compile_to_wasm_valid_module() {
    let func = make_main_returning(42);
    let wasm = compile_to_wasm(&[func]).expect("compilation should succeed");

    // Basic header check
    assert!(wasm.len() > 8, "Module should be non-trivial");
    assert_eq!(&wasm[0..4], &WASM_MAGIC, "Should start with Wasm magic");
    assert_eq!(&wasm[4..8], &WASM_VERSION, "Should have Wasm version 1");

    // Parse all sections and verify required ones exist
    let sections = parse_sections(&wasm);
    let section_ids: Vec<u8> = sections.iter().map(|s| s.id).collect();

    let required_sections = [
        (SECTION_TYPE, "Type"),
        (SECTION_IMPORT, "Import"),
        (SECTION_FUNCTION, "Function"),
        (SECTION_MEMORY, "Memory"),
        (SECTION_GLOBAL, "Global"),
        (SECTION_EXPORT, "Export"),
        (SECTION_START, "Start"),
        (SECTION_CODE, "Code"),
    ];

    for (id, name) in &required_sections {
        assert!(
            section_ids.contains(id),
            "Module should contain {} section (ID {}), found sections: {:?}",
            name,
            id,
            section_ids
        );
    }

    // Sections should be in non-decreasing order
    for window in section_ids.windows(2) {
        assert!(
            window[0] <= window[1],
            "Sections should be in ascending order, but {} came after {}",
            window[1],
            window[0]
        );
    }

    // Re-parse by iterating to the end without panicking (well-formedness)
    let mut offset = 8usize;
    let mut total_bytes = 0usize;
    while offset < wasm.len() {
        let _section_id = wasm[offset];
        offset += 1;
        let (size, size_len) = decode_unsigned_leb128(&wasm[offset..]);
        offset += size_len;
        offset += size as usize;
        total_bytes += 1;
    }
    assert_eq!(offset, wasm.len(), "Module should be fully consumable");
    assert!(
        total_bytes >= 8,
        "Module should have at least 8 sections, got {}",
        total_bytes
    );
}

// ===========================================================================
// Test 12: Simple return value programs compile and validate
// ===========================================================================

/// Test: Compile multiple simple i32-returning programs and verify each
/// produces a valid Wasm module with correct structure.
#[test]
fn test_compile_to_wasm_simple_return_values() {
    let test_values: Vec<i32> = vec![0, 1, 42, 127, 128, 255, 256, -1, -42];

    for value in test_values {
        let func = make_main_returning(value);
        let wasm = compile_to_wasm(&[func]).unwrap_or_else(|e| {
            panic!(
                "compile_to_wasm should succeed for main() -> i32 {{ return {}; }}: {:?}",
                value, e
            )
        });

        // Every compiled module must start with the correct header
        assert_eq!(
            &wasm[0..4],
            &WASM_MAGIC,
            "Module for return value {} should start with Wasm magic",
            value
        );
        assert_eq!(
            &wasm[4..8],
            &WASM_VERSION,
            "Module for return value {} should have Wasm version 1",
            value
        );

        // Must be a reasonable size (at least header + a few sections)
        assert!(
            wasm.len() > 50,
            "Module for return value {} should be non-trivial (got {} bytes)",
            value,
            wasm.len()
        );

        // Must have code section
        let sections = parse_sections(&wasm);
        assert!(
            find_section(&sections, SECTION_CODE).is_some(),
            "Module for return value {} should contain a code section",
            value
        );

        // Must export _start
        if let Some(export_section) = find_section(&sections, SECTION_EXPORT) {
            let exports = parse_exports(&export_section.content);
            assert!(
                exports.iter().any(|e| e.name == "_start"),
                "Module for return value {} should export '_start'",
                value
            );
        } else {
            panic!(
                "Module for return value {} should have an export section",
                value
            );
        }
    }
}
