//! # VUMA Package Manager
//!
//! Provides the package management infrastructure for the VUMA ecosystem:
//!
//! - **`vuma.pkg` manifest** — TOML-based package descriptor (name, version,
//!   dependencies, targets)
//! - **`PackageManifest`** — parsed representation of a `vuma.pkg` file
//! - **`DependencyResolver`** — resolves package dependencies from a registry
//!   (local file-based for now)
//! - **`PackageRegistry`** — simple local file-based registry at `~/.vuma/registry/`
//!
//! # CLI Integration
//!
//! The package manager is wired into the `vuma pkg` subcommand:
//!
//! ```text
//! vuma pkg init           — Create a new vuma.pkg in the current directory
//! vuma pkg build          — Build the package and its dependencies
//! vuma pkg add <dep>      — Add a dependency to vuma.pkg
//! ```

#[macro_use]
mod vuma_log_w44 {
    /// VUMA-native logging macro (Wave 44). Replaces the `log` crate in core
    /// crates. No-op in release builds (format args still type-checked via
    /// `format_args!`); `eprintln!` in debug. Not `#[macro_export]` to avoid
    /// cross-crate name collisions — each core crate carries its own copy.
    macro_rules! vuma_log {
        ($level:ident, $($arg:tt)*) => {{
            #[cfg(debug_assertions)]
            eprintln!("[{}] {}", stringify!($level), format!($($arg)*));
            #[cfg(not(debug_assertions))]
            { let _ = format_args!($($arg)*); }
        }};
    }
}
pub mod manifest;
pub mod registry;
pub mod resolver;
mod toml_lite;

pub use manifest::{PackageManifest, PackageTarget, Dependency, TargetKind, parse_manifest};
pub use registry::PackageRegistry;
pub use resolver::{DependencyResolver, ResolveResult, resolve_dependencies};

// Wave 41: `thiserror` removed in favor of hand-written `Display` +
// `std::error::Error` impls (matches the pattern established in
// `src/scg/src/graph.rs:SCGError`).

/// Errors that can occur during package operations.
#[derive(Debug)]
pub enum PackageError {
    /// I/O error reading or writing files.
    Io(std::io::Error),

    /// Error parsing a `vuma.pkg` TOML file.
    ManifestParse(String),

    /// A dependency was not found in the registry.
    DependencyNotFound(String, String),

    /// A version conflict was detected during resolution.
    VersionConflict {
        /// Package name.
        name: String,
        /// Required version string.
        required: String,
        /// Version found in the registry.
        found: String,
    },

    /// A circular dependency was detected.
    CircularDependency(String),

    /// The package directory already exists.
    AlreadyExists(String),

    /// Generic package error.
    Other(String),
}

impl std::fmt::Display for PackageError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PackageError::Io(e) => write!(f, "I/O error: {e}"),
            PackageError::ManifestParse(msg) => write!(f, "manifest parse error: {msg}"),
            PackageError::DependencyNotFound(name, version) => {
                write!(f, "dependency not found: {name}@{version}")
            }
            PackageError::VersionConflict { name, required, found } => {
                write!(
                    f,
                    "version conflict for {name}: required {required}, found {found}"
                )
            }
            PackageError::CircularDependency(chain) => {
                write!(f, "circular dependency detected: {chain}")
            }
            PackageError::AlreadyExists(path) => write!(f, "package already exists: {path}"),
            PackageError::Other(msg) => write!(f, "{msg}"),
        }
    }
}

impl std::error::Error for PackageError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            PackageError::Io(e) => Some(e),
            _ => None,
        }
    }
}

// Replaces the `#[from] std::io::Error` attribute previously generated by
// `thiserror`. Required so the `?` operator continues to work at the call
// sites in `lib.rs`, `registry.rs`, and `manifest.rs` that propagate
// `std::io::Result` values into `PackageResult<_>`.
impl From<std::io::Error> for PackageError {
    fn from(e: std::io::Error) -> Self {
        PackageError::Io(e)
    }
}

/// Result type for package operations.
pub type PackageResult<T> = Result<T, PackageError>;

/// Initialize a new package in the given directory.
///
/// Creates a `vuma.pkg` manifest file with default values.
pub fn init_package(dir: &std::path::Path, name: &str) -> PackageResult<()> {
    let pkg_path = dir.join("vuma.pkg");
    if pkg_path.exists() {
        return Err(PackageError::AlreadyExists(pkg_path.display().to_string()));
    }

    let manifest = PackageManifest {
        name: name.to_string(),
        version: "0.1.0".to_string(),
        description: Some(format!("VUMA package: {}", name)),
        dependencies: Vec::new(),
        targets: vec![PackageTarget {
            name: name.to_string(),
            kind: TargetKind::Bin,
            src: "src/main.vuma".to_string(),
        }],
    };

    let toml_str = manifest.to_toml().map_err(|e| PackageError::ManifestParse(e.to_string()))?;
    std::fs::write(&pkg_path, toml_str)?;

    // Create src directory
    let src_dir = dir.join("src");
    if !src_dir.exists() {
        std::fs::create_dir_all(&src_dir)?;
    }

    // Create a minimal main.vuma
    let main_path = src_dir.join("main.vuma");
    if !main_path.exists() {
        std::fs::write(&main_path, "fn main() {\n    // Entry point\n}\n")?;
    }

    Ok(())
}

/// Add a dependency to the package manifest in the given directory.
pub fn add_dependency(dir: &std::path::Path, dep_name: &str, version: &str) -> PackageResult<()> {
    let pkg_path = dir.join("vuma.pkg");
    if !pkg_path.exists() {
        return Err(PackageError::ManifestParse(
            "no vuma.pkg found in the current directory".to_string(),
        ));
    }

    let content = std::fs::read_to_string(&pkg_path)?;
    let mut manifest = PackageManifest::from_toml(&content)
        .map_err(|e| PackageError::ManifestParse(e.to_string()))?;

    // Check if dependency already exists
    if manifest.dependencies.iter().any(|d| d.name == dep_name) {
        return Err(PackageError::Other(format!(
            "dependency '{}' already exists",
            dep_name
        )));
    }

    manifest.dependencies.push(Dependency {
        name: dep_name.to_string(),
        version: version.to_string(),
        registry: None,
    });

    let toml_str = manifest.to_toml().map_err(|e| PackageError::ManifestParse(e.to_string()))?;
    std::fs::write(&pkg_path, toml_str)?;

    Ok(())
}

/// Build the package in the given directory.
///
/// Resolves dependencies, then compiles all targets.
pub fn build_package(dir: &std::path::Path) -> PackageResult<()> {
    let pkg_path = dir.join("vuma.pkg");
    if !pkg_path.exists() {
        return Err(PackageError::ManifestParse(
            "no vuma.pkg found in the current directory".to_string(),
        ));
    }

    let content = std::fs::read_to_string(&pkg_path)?;
    let manifest = PackageManifest::from_toml(&content)
        .map_err(|e| PackageError::ManifestParse(e.to_string()))?;

    vuma_log!(info, "Building package {} v{}", manifest.name, manifest.version);

    // Resolve dependencies
    let registry = PackageRegistry::default();
    let resolver = DependencyResolver::new(registry);
    let resolved = resolver.resolve(&manifest)?;

    if !resolved.packages.is_empty() {
        vuma_log!(info, "Resolved {} dependencies:", resolved.packages.len());
        for pkg in &resolved.packages {
            vuma_log!(info, "  {} v{}", pkg.name, pkg.version);
        }
    }

    // Build each target
    for target in &manifest.targets {
        vuma_log!(info, "Building target: {} ({:?})", target.name, target.kind);
        let src_path = dir.join(&target.src);
        if !src_path.exists() {
            vuma_log!(warn, "Source file not found: {}", src_path.display());
        }
        // The actual compilation would be delegated to the main pipeline.
        // For now we just validate the manifest and resolve deps.
    }

    Ok(())
}
