#!/usr/bin/env python3
"""spirv_to_vuma.py — Convert SPIR-V bytecode files to VUMA const byte arrays.

Usage:
    python3 scripts/spirv_to_vuma.py shaders/*.spv > womb/ui/render/shaders_spirv.vuma

This script is the build-time bridge between glslangValidator's SPIR-V
output and VUMA's const byte array embedding (V-26 Phase 2, ADR-0022).

Each .spv file is read as raw bytes, converted to a hex-literal array,
and emitted as a VUMA const declaration:

    const PATH_TESSELLATE_SPIRV: [u8; 8192] = [0x03, 0x02, 0x23, 0x07, /* ... */];

The const name is derived from the filename (PATH_TESSELLATE_SPIRV for
path_tessellate.spv). The array length is the exact SPIR-V bytecode size.

ADR-0022 §What VEEE provides:
    "The #[embed("file.spv")] attribute that pulls in a pre-compiled
     SPIR-V file as a const byte array."

This script is the build-time implementation of that embedding. It runs
once at build time (invoked by the Makefile target `generate_spirv_consts`)
and its output is checked into the repo as
`womb/ui/render/shaders_spirv.vuma`.

The generated const arrays are then referenced by VUMA programs via
`gpu_dispatch` host imports (womb/ui/render/gpu_dispatch.vuma) which
pass the const byte array's address + length to the C host runtime's
Vulkan/Metal/WebGPU functions.
"""

import sys
import os
import struct
from pathlib import Path


def spirv_to_const_decl(spv_path: Path) -> str:
    """Convert a single .spv file to a VUMA const declaration string."""
    # Read the SPIR-V bytecode.
    data = spv_path.read_bytes()

    # Derive the const name from the filename.
    # path_tessellate.spv → PATH_TESSELLATE_SPIRV
    stem = spv_path.stem.upper().replace("-", "_")
    const_name = f"{stem}_SPIRV"

    # Validate SPIR-V magic number (little-endian: 0x07230203).
    if len(data) < 4:
        raise ValueError(f"{spv_path}: too short for SPIR-V magic")
    magic = struct.unpack("<I", data[:4])[0]
    if magic != 0x07230203:
        raise ValueError(
            f"{spv_path}: bad SPIR-V magic (got 0x{magic:08x}, expected 0x07230203)"
        )

    # Format the bytes as hex literals, 12 per line.
    hex_literals = []
    for i, b in enumerate(data):
        hex_literals.append(f"0x{b:02x}")
    # Group into lines of 12 elements for readability.
    lines = []
    for i in range(0, len(hex_literals), 12):
        chunk = hex_literals[i : i + 12]
        lines.append("    " + ", ".join(chunk) + ",")
    # Remove trailing comma from the last line.
    if lines:
        lines[-1] = lines[-1].rstrip(",")

    array_body = "\n".join(lines)

    return f"""// Generated by scripts/spirv_to_vuma.py from {spv_path.name}
// SPIR-V bytecode size: {len(data)} bytes
// DO NOT EDIT — regenerate via: make generate_spirv_consts
const {const_name}: [u8; {len(data)}] = [
{array_body}
];
"""


def main():
    if len(sys.argv) < 2:
        print(
            "Usage: spirv_to_vuma.py <file.spv> [<file.spv> ...] > output.vuma",
            file=sys.stderr,
        )
        sys.exit(1)

    spv_files = [Path(f) for f in sys.argv[1:]]

    # Header comment for the generated file.
    print("// ============================================================================")
    print("// womb/ui/render/shaders_spirv.vuma — Generated SPIR-V const byte arrays")
    print("// ============================================================================")
    print("//")
    print("// This file is GENERATED by scripts/spirv_to_vuma.py from the .glsl")
    print("// shader sources in womb/ui/render/shaders/. Do not edit by hand.")
    print("//")
    print("// Regenerate via:  make generate_spirv_consts")
    print("//")
    print("// Each const is a [u8; N] array containing the raw SPIR-V bytecode")
    print("// produced by glslangValidator. The VUMA program passes the const's")
    print("// address + length to gpu_dispatch host imports (Vulkan/Metal/WebGPU).")
    print("//")
    print("// ADR-0022: Hand-written SPIR-V backend (supersedes ADR-0018 MLIR).")
    print("// V-26 Phase 2: Lit::Bytes lowers through .rodata emission path.")
    print("")

    for spv_path in spv_files:
        if not spv_path.exists():
            print(f"error: {spv_path}: file not found", file=sys.stderr)
            sys.exit(1)
        try:
            decl = spirv_to_const_decl(spv_path)
            print(decl)
        except ValueError as e:
            print(f"error: {e}", file=sys.stderr)
            sys.exit(1)


if __name__ == "__main__":
    main()
